apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jankenpon-gateway
  namespace: default
  labels:
    app: jankenpon-gateway
spec:
  selector:
    matchLabels:
      app: jankenpon-gateway
  template:
    metadata:
      labels:
        app: jankenpon-gateway
    spec:
      containers:
      - image: kurai/jankenpon-gateway-arm
        name: gateway
        ports:
        - containerPort: 3030
          name: http
          protocol: TCP
